export type AirportRecord = Readonly<{
  iata: string;
  icao?: string;
  name: string;
  cityName: string;
  citySlug: string;
  countryName: string;
  countryIso2: string;
  latitude: number;
  longitude: number;
  type: "large_airport" | "medium_airport" | "small_airport";
}>;

export type CityRecord = Readonly<{
  cityName: string;
  citySlug: string;
  countryName: string;
  countryIso2: string;
  primaryIata: string;
  airportCount: number;
  latitude: number;
  longitude: number;
}>;

/**
 * Curated local fixture of representative global hub airports and regional airports for development and CI testing.
 * On Staging and Production, live queries resolve against the full PostgreSQL backend database.
 */
export const AIRPORTS_CATALOG: readonly AirportRecord[] = [
  // Europe
  {
    iata: "LHR",
    icao: "EGLL",
    name: "Heathrow Airport",
    cityName: "London",
    citySlug: "london",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 51.47,
    longitude: -0.4543,
    type: "large_airport",
  },
  {
    iata: "LGW",
    icao: "EGKK",
    name: "Gatwick Airport",
    cityName: "London",
    citySlug: "london",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 51.1481,
    longitude: -0.1903,
    type: "large_airport",
  },
  {
    iata: "STN",
    icao: "EGSS",
    name: "Stansted Airport",
    cityName: "London",
    citySlug: "london",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 51.8860,
    longitude: 0.2389,
    type: "large_airport",
  },
  {
    iata: "LTN",
    icao: "EGGW",
    name: "Luton Airport",
    cityName: "London",
    citySlug: "london",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 51.8747,
    longitude: -0.3683,
    type: "large_airport",
  },
  {
    iata: "GLA",
    icao: "EGPF",
    name: "Glasgow Airport",
    cityName: "Glasgow",
    citySlug: "glasgow",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 55.8719,
    longitude: -4.4331,
    type: "large_airport",
  },
  {
    iata: "CDG",
    icao: "LFPG",
    name: "Charles de Gaulle Airport",
    cityName: "Paris",
    citySlug: "paris",
    countryName: "France",
    countryIso2: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
    type: "large_airport",
  },
  {
    iata: "ORY",
    icao: "LFPO",
    name: "Paris Orly Airport",
    cityName: "Paris",
    citySlug: "paris",
    countryName: "France",
    countryIso2: "FR",
    latitude: 48.7233,
    longitude: 2.3794,
    type: "large_airport",
  },
  {
    iata: "FRA",
    icao: "EDDF",
    name: "Frankfurt Airport",
    cityName: "Frankfurt",
    citySlug: "frankfurt",
    countryName: "Germany",
    countryIso2: "DE",
    latitude: 50.0379,
    longitude: 8.5622,
    type: "large_airport",
  },
  {
    iata: "AMS",
    icao: "EHAM",
    name: "Amsterdam Airport Schiphol",
    cityName: "Amsterdam",
    citySlug: "amsterdam",
    countryName: "Netherlands",
    countryIso2: "NL",
    latitude: 52.3105,
    longitude: 4.7683,
    type: "large_airport",
  },
  {
    iata: "GVA",
    icao: "LSGG",
    name: "Geneva Airport",
    cityName: "Geneva",
    citySlug: "geneva",
    countryName: "Switzerland",
    countryIso2: "CH",
    latitude: 46.2381,
    longitude: 6.1089,
    type: "large_airport",
  },
  {
    iata: "ZRH",
    icao: "LSZH",
    name: "Zurich Airport",
    cityName: "Zurich",
    citySlug: "zurich",
    countryName: "Switzerland",
    countryIso2: "CH",
    latitude: 47.4647,
    longitude: 8.5492,
    type: "large_airport",
  },
  {
    iata: "FCO",
    icao: "LIRF",
    name: "Leonardo da Vinci–Fiumicino Airport",
    cityName: "Rome",
    citySlug: "rome",
    countryName: "Italy",
    countryIso2: "IT",
    latitude: 41.8003,
    longitude: 12.2389,
    type: "large_airport",
  },
  {
    iata: "BCN",
    icao: "LEBL",
    name: "Josep Tarradellas Barcelona-El Prat Airport",
    cityName: "Barcelona",
    citySlug: "barcelona",
    countryName: "Spain",
    countryIso2: "ES",
    latitude: 41.2974,
    longitude: 2.0833,
    type: "large_airport",
  },
  {
    iata: "MAD",
    icao: "LEMD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    cityName: "Madrid",
    citySlug: "madrid",
    countryName: "Spain",
    countryIso2: "ES",
    latitude: 40.4839,
    longitude: -3.5680,
    type: "large_airport",
  },
  {
    iata: "KUO",
    icao: "EFKU",
    name: "Kuopio Airport",
    cityName: "Kuopio",
    citySlug: "kuopio",
    countryName: "Finland",
    countryIso2: "FI",
    latitude: 63.0072,
    longitude: 27.7978,
    type: "medium_airport",
  },
  {
    iata: "KUT",
    icao: "UGKO",
    name: "Kutaisi International Airport",
    cityName: "Kutaisi",
    citySlug: "kutaisi",
    countryName: "Georgia",
    countryIso2: "GE",
    latitude: 42.1764,
    longitude: 42.4828,
    type: "medium_airport",
  },
  {
    iata: "IST",
    icao: "LTFM",
    name: "Istanbul Airport",
    cityName: "Istanbul",
    citySlug: "istanbul",
    countryName: "Turkey",
    countryIso2: "TR",
    latitude: 41.2753,
    longitude: 28.7519,
    type: "large_airport",
  },

  // Asia Pacific
  {
    iata: "SIN",
    icao: "WSSS",
    name: "Singapore Changi Airport",
    cityName: "Singapore",
    citySlug: "singapore",
    countryName: "Singapore",
    countryIso2: "SG",
    latitude: 1.3644,
    longitude: 103.9915,
    type: "large_airport",
  },
  {
    iata: "KUL",
    icao: "WMKK",
    name: "Kuala Lumpur International Airport",
    cityName: "Kuala Lumpur",
    citySlug: "kuala-lumpur",
    countryName: "Malaysia",
    countryIso2: "MY",
    latitude: 2.7456,
    longitude: 101.7072,
    type: "large_airport",
  },
  {
    iata: "SZB",
    icao: "WMSA",
    name: "Kuala Lumpur Sultan Abdul Aziz Shah Airport",
    cityName: "Kuala Lumpur",
    citySlug: "kuala-lumpur",
    countryName: "Malaysia",
    countryIso2: "MY",
    latitude: 3.13,
    longitude: 101.55,
    type: "medium_airport",
  },
  {
    iata: "BKK",
    icao: "VTBS",
    name: "Suvarnabhumi Airport",
    cityName: "Bangkok",
    citySlug: "bangkok",
    countryName: "Thailand",
    countryIso2: "TH",
    latitude: 13.69,
    longitude: 100.7501,
    type: "large_airport",
  },
  {
    iata: "DMK",
    icao: "VTBD",
    name: "Don Mueang International Airport",
    cityName: "Bangkok",
    citySlug: "bangkok",
    countryName: "Thailand",
    countryIso2: "TH",
    latitude: 13.9126,
    longitude: 100.6067,
    type: "large_airport",
  },
  {
    iata: "HKT",
    icao: "VTSP",
    name: "Phuket International Airport",
    cityName: "Phuket",
    citySlug: "phuket",
    countryName: "Thailand",
    countryIso2: "TH",
    latitude: 8.1132,
    longitude: 98.3169,
    type: "large_airport",
  },
  {
    iata: "HND",
    icao: "RJTT",
    name: "Tokyo Haneda Airport",
    cityName: "Tokyo",
    citySlug: "tokyo",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 35.5494,
    longitude: 139.7798,
    type: "large_airport",
  },
  {
    iata: "NRT",
    icao: "RJAA",
    name: "Narita International Airport",
    cityName: "Tokyo",
    citySlug: "tokyo",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 35.7647,
    longitude: 140.3863,
    type: "large_airport",
  },
  {
    iata: "KUH",
    icao: "RJCK",
    name: "Kushiro Airport",
    cityName: "Kushiro",
    citySlug: "kushiro",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 43.0411,
    longitude: 144.1931,
    type: "medium_airport",
  },
  {
    iata: "KIX",
    icao: "RJBB",
    name: "Kansai International Airport",
    cityName: "Osaka",
    citySlug: "osaka",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 34.4347,
    longitude: 135.2442,
    type: "large_airport",
  },
  {
    iata: "FUK",
    icao: "RJFF",
    name: "Fukuoka Airport",
    cityName: "Fukuoka",
    citySlug: "fukuoka",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 33.5859,
    longitude: 130.4507,
    type: "large_airport",
  },
  {
    iata: "ICN",
    icao: "RKSI",
    name: "Incheon International Airport",
    cityName: "Seoul",
    citySlug: "seoul",
    countryName: "South Korea",
    countryIso2: "KR",
    latitude: 37.4602,
    longitude: 126.4407,
    type: "large_airport",
  },
  {
    iata: "GMP",
    icao: "RKSS",
    name: "Gimpo International Airport",
    cityName: "Seoul",
    citySlug: "seoul",
    countryName: "South Korea",
    countryIso2: "KR",
    latitude: 37.5583,
    longitude: 126.7906,
    type: "large_airport",
  },
  {
    iata: "PUS",
    icao: "RKPK",
    name: "Gimhae International Airport",
    cityName: "Busan",
    citySlug: "busan",
    countryName: "South Korea",
    countryIso2: "KR",
    latitude: 35.1795,
    longitude: 128.9382,
    type: "large_airport",
  },
  {
    iata: "CAN",
    icao: "ZGGG",
    name: "Guangzhou Baiyun International Airport",
    cityName: "Guangzhou",
    citySlug: "guangzhou",
    countryName: "China",
    countryIso2: "CN",
    latitude: 23.3924,
    longitude: 113.2988,
    type: "large_airport",
  },
  {
    iata: "HKG",
    icao: "VHHH",
    name: "Hong Kong International Airport",
    cityName: "Hong Kong",
    citySlug: "hong-kong",
    countryName: "Hong Kong",
    countryIso2: "HK",
    latitude: 22.308,
    longitude: 113.9185,
    type: "large_airport",
  },
  {
    iata: "TPE",
    icao: "RCTP",
    name: "Taiwan Taoyuan International Airport",
    cityName: "Taipei",
    citySlug: "taipei",
    countryName: "Taiwan",
    countryIso2: "TW",
    latitude: 25.0797,
    longitude: 121.2342,
    type: "large_airport",
  },
  {
    iata: "DEL",
    icao: "VIDP",
    name: "Indira Gandhi International Airport",
    cityName: "New Delhi",
    citySlug: "new-delhi",
    countryName: "India",
    countryIso2: "IN",
    latitude: 28.5562,
    longitude: 77.1000,
    type: "large_airport",
  },
  {
    iata: "BOM",
    icao: "VABB",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    cityName: "Mumbai",
    citySlug: "mumbai",
    countryName: "India",
    countryIso2: "IN",
    latitude: 19.0896,
    longitude: 72.8656,
    type: "large_airport",
  },
  {
    iata: "KUU",
    icao: "VIBR",
    name: "Kullu–Manali Airport",
    cityName: "Kullu-Manali",
    citySlug: "kullu-manali",
    countryName: "India",
    countryIso2: "IN",
    latitude: 31.8767,
    longitude: 77.1544,
    type: "medium_airport",
  },
  {
    iata: "DPS",
    icao: "WADD",
    name: "Ngurah Rai International Airport",
    cityName: "Bali",
    citySlug: "bali",
    countryName: "Indonesia",
    countryIso2: "ID",
    latitude: -8.7482,
    longitude: 115.1672,
    type: "large_airport",
  },
  {
    iata: "CGK",
    icao: "WIII",
    name: "Soekarno–Hatta International Airport",
    cityName: "Jakarta",
    citySlug: "jakarta",
    countryName: "Indonesia",
    countryIso2: "ID",
    latitude: -6.1256,
    longitude: 106.6558,
    type: "large_airport",
  },
  {
    iata: "MNL",
    icao: "RPLL",
    name: "Ninoy Aquino International Airport",
    cityName: "Manila",
    citySlug: "manila",
    countryName: "Philippines",
    countryIso2: "PH",
    latitude: 14.5086,
    longitude: 121.0194,
    type: "large_airport",
  },
  {
    iata: "SYD",
    icao: "YSSY",
    name: "Sydney Kingsford Smith Airport",
    cityName: "Sydney",
    citySlug: "sydney",
    countryName: "Australia",
    countryIso2: "AU",
    latitude: -33.9399,
    longitude: 151.1753,
    type: "large_airport",
  },
  {
    iata: "MEL",
    icao: "YMML",
    name: "Melbourne Airport",
    cityName: "Melbourne",
    citySlug: "melbourne",
    countryName: "Australia",
    countryIso2: "AU",
    latitude: -37.6690,
    longitude: 144.8410,
    type: "large_airport",
  },
  {
    iata: "OOL",
    icao: "YBCG",
    name: "Gold Coast Airport",
    cityName: "Gold Coast",
    citySlug: "gold-coast",
    countryName: "Australia",
    countryIso2: "AU",
    latitude: -28.1644,
    longitude: 153.5047,
    type: "large_airport",
  },

  // Middle East
  {
    iata: "DXB",
    icao: "OMDB",
    name: "Dubai International Airport",
    cityName: "Dubai",
    citySlug: "dubai",
    countryName: "United Arab Emirates",
    countryIso2: "AE",
    latitude: 25.2532,
    longitude: 55.3657,
    type: "large_airport",
  },
  {
    iata: "DOH",
    icao: "OTHH",
    name: "Hamad International Airport",
    cityName: "Doha",
    citySlug: "doha",
    countryName: "Qatar",
    countryIso2: "QA",
    latitude: 25.2731,
    longitude: 51.6081,
    type: "large_airport",
  },

  // Americas
  {
    iata: "JFK",
    icao: "KJFK",
    name: "John F. Kennedy International Airport",
    cityName: "New York",
    citySlug: "new-york",
    countryName: "United States",
    countryIso2: "US",
    latitude: 40.6413,
    longitude: -73.7781,
    type: "large_airport",
  },
  {
    iata: "EWR",
    icao: "KEWR",
    name: "Newark Liberty International Airport",
    cityName: "New York",
    citySlug: "new-york",
    countryName: "United States",
    countryIso2: "US",
    latitude: 40.6895,
    longitude: -74.1745,
    type: "large_airport",
  },
  {
    iata: "LAX",
    icao: "KLAX",
    name: "Los Angeles International Airport",
    cityName: "Los Angeles",
    citySlug: "los-angeles",
    countryName: "United States",
    countryIso2: "US",
    latitude: 33.9416,
    longitude: -118.4085,
    type: "large_airport",
  },
  {
    iata: "SFO",
    icao: "KSFO",
    name: "San Francisco International Airport",
    cityName: "San Francisco",
    citySlug: "san-francisco",
    countryName: "United States",
    countryIso2: "US",
    latitude: 37.6213,
    longitude: -122.3790,
    type: "large_airport",
  },
  {
    iata: "ORD",
    icao: "KORD",
    name: "O'Hare International Airport",
    cityName: "Chicago",
    citySlug: "chicago",
    countryName: "United States",
    countryIso2: "US",
    latitude: 41.9742,
    longitude: -87.9073,
    type: "large_airport",
  },
  {
    iata: "GRU",
    icao: "SBGR",
    name: "São Paulo/Guarulhos International Airport",
    cityName: "São Paulo",
    citySlug: "sao-paulo",
    countryName: "Brazil",
    countryIso2: "BR",
    latitude: -23.4356,
    longitude: -46.4731,
    type: "large_airport",
  },
  {
    iata: "GDL",
    icao: "MMGL",
    name: "Guadalajara International Airport",
    cityName: "Guadalajara",
    citySlug: "guadalajara",
    countryName: "Mexico",
    countryIso2: "MX",
    latitude: 20.5218,
    longitude: -103.3111,
    type: "large_airport",
  },

  // Regional Airports (e.g. Vietnam)
  {
    iata: "DAD",
    icao: "VVDN",
    name: "Da Nang International Airport",
    cityName: "Da Nang",
    citySlug: "da-nang",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 16.0439,
    longitude: 108.198997,
    type: "large_airport",
  },
  {
    iata: "HUI",
    icao: "VVPB",
    name: "Phu Bai International Airport",
    cityName: "Hue",
    citySlug: "hue",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 16.400628,
    longitude: 107.703094,
    type: "medium_airport",
  },
  {
    iata: "VCL",
    icao: "VVCL",
    name: "Chu Lai Airport",
    cityName: "Tam Ky",
    citySlug: "tam-ky",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 15.406111,
    longitude: 108.705556,
    type: "medium_airport",
  },
  {
    iata: "UIH",
    icao: "VVPC",
    name: "Phu Cat Airport",
    cityName: "Quy Nhon",
    citySlug: "quy-nhon",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 13.955,
    longitude: 109.042,
    type: "medium_airport",
  },
  {
    iata: "HAN",
    icao: "VVNB",
    name: "Noi Bai International Airport",
    cityName: "Hanoi",
    citySlug: "hanoi",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 21.221201,
    longitude: 105.806999,
    type: "large_airport",
  },
  {
    iata: "SGN",
    icao: "VVTS",
    name: "Tan Son Nhat International Airport",
    cityName: "Ho Chi Minh City",
    citySlug: "ho-chi-minh-city",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 10.8188,
    longitude: 106.6519,
    type: "large_airport",
  },
  {
    iata: "CXR",
    icao: "VVCR",
    name: "Cam Ranh International Airport",
    cityName: "Nha Trang",
    citySlug: "nha-trang",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 11.9982,
    longitude: 109.219002,
    type: "large_airport",
  },
] as const;

/**
 * Derives unique cities from the airport catalog.
 */
export const CITIES_CATALOG: readonly CityRecord[] = Array.from(
  AIRPORTS_CATALOG.reduce((map, airport) => {
    const existing = map.get(airport.citySlug);
    if (existing) {
      map.set(airport.citySlug, {
        ...existing,
        airportCount: existing.airportCount + 1,
      });
    } else {
      map.set(airport.citySlug, {
        cityName: airport.cityName,
        citySlug: airport.citySlug,
        countryName: airport.countryName,
        countryIso2: airport.countryIso2,
        primaryIata: airport.iata,
        airportCount: 1,
        latitude: airport.latitude,
        longitude: airport.longitude,
      });
    }
    return map;
  }, new Map<string, CityRecord>()).values(),
);
