export type HubAirport = Readonly<{
  iata: string;
  name: string;
  cityName: string;
  citySlug: string;
  countryName: string;
  countryIso2: string;
  latitude: number;
  longitude: number;
}>;

export type HomepageDestination = Readonly<{
  cityName: string;
  citySlug: string;
  iata: string;
  airportName: string;
  countryName: string;
  countryIso2: string;
  latitude: number;
  longitude: number;
  typicalDuration: string; // e.g. "13h 05m"
  durationRange: string; // e.g. "12h - 14h"
  shortestDurationMinutes: number;
  airlines: readonly string[]; // e.g. ["SQ", "BA"]
  distanceKm: number;
  routePath: string;
}>;

export type HubRouteNetwork = Readonly<{
  origin: HubAirport;
  destinations: readonly HomepageDestination[];
}>;

export type PopularRouteCard = Readonly<{
  originIata: string;
  originCity: string;
  destinationIata: string;
  destinationCity: string;
  airlines: readonly string[];
  distanceKm: number;
  duration: string;
  routePath: string;
}>;

export type PopularCityItem = Readonly<{
  name: string;
  slug: string;
  iata: string;
  country: string;
}>;

export const POPULAR_CITIES: readonly PopularCityItem[] = [
  { name: "London", slug: "london", iata: "LHR", country: "United Kingdom" },
  { name: "Tokyo", slug: "tokyo", iata: "HND", country: "Japan" },
  { name: "Bangkok", slug: "bangkok", iata: "BKK", country: "Thailand" },
  { name: "Paris", slug: "paris", iata: "CDG", country: "France" },
  { name: "Dubai", slug: "dubai", iata: "DXB", country: "United Arab Emirates" },
  { name: "New York", slug: "new-york", iata: "JFK", country: "United States" },
] as const;

export const POPULAR_ROUTES: readonly PopularRouteCard[] = [
  {
    originIata: "LHR",
    originCity: "London",
    destinationIata: "SIN",
    destinationCity: "Singapore",
    airlines: ["SQ", "BA", "QF"],
    distanceKm: 10889,
    duration: "13h 05m",
    routePath: "/flights/london-to-singapore",
  },
  {
    originIata: "JFK",
    originCity: "New York",
    destinationIata: "CDG",
    destinationCity: "Paris",
    airlines: ["AF", "DL", "AA"],
    distanceKm: 5836,
    duration: "7h 20m",
    routePath: "/flights/new-york-to-paris",
  },
  {
    originIata: "HND",
    originCity: "Tokyo",
    destinationIata: "SYD",
    destinationCity: "Sydney",
    airlines: ["NH", "JL", "QF"],
    distanceKm: 7829,
    duration: "9h 45m",
    routePath: "/flights/tokyo-to-sydney",
  },
] as const;

export const HUB_AIRPORTS: readonly HubAirport[] = [
  {
    iata: "LHR",
    name: "Heathrow Airport",
    cityName: "London",
    citySlug: "london",
    countryName: "United Kingdom",
    countryIso2: "GB",
    latitude: 51.47,
    longitude: -0.4543,
  },
  {
    iata: "SIN",
    name: "Singapore Changi Airport",
    cityName: "Singapore",
    citySlug: "singapore",
    countryName: "Singapore",
    countryIso2: "SG",
    latitude: 1.3644,
    longitude: 103.9915,
  },
  {
    iata: "HND",
    name: "Haneda Airport",
    cityName: "Tokyo",
    citySlug: "tokyo",
    countryName: "Japan",
    countryIso2: "JP",
    latitude: 35.5494,
    longitude: 139.7798,
  },
  {
    iata: "JFK",
    name: "John F. Kennedy International Airport",
    cityName: "New York",
    citySlug: "new-york",
    countryName: "United States",
    countryIso2: "US",
    latitude: 40.6413,
    longitude: -73.7781,
  },
  {
    iata: "BKK",
    name: "Suvarnabhumi Airport",
    cityName: "Bangkok",
    citySlug: "bangkok",
    countryName: "Thailand",
    countryIso2: "TH",
    latitude: 13.69,
    longitude: 100.7501,
  },
  {
    iata: "CDG",
    name: "Charles de Gaulle Airport",
    cityName: "Paris",
    citySlug: "paris",
    countryName: "France",
    countryIso2: "FR",
    latitude: 49.0097,
    longitude: 2.5479,
  },
  {
    iata: "DXB",
    name: "Dubai International Airport",
    cityName: "Dubai",
    citySlug: "dubai",
    countryName: "United Arab Emirates",
    countryIso2: "AE",
    latitude: 25.2532,
    longitude: 55.3657,
  },
  {
    iata: "SGN",
    name: "Tan Son Nhat International Airport",
    cityName: "Ho Chi Minh City",
    citySlug: "ho-chi-minh-city",
    countryName: "Vietnam",
    countryIso2: "VN",
    latitude: 10.8188,
    longitude: 106.6519,
  },
  {
    iata: "SYD",
    name: "Sydney Kingsford Smith Airport",
    cityName: "Sydney",
    citySlug: "sydney",
    countryName: "Australia",
    countryIso2: "AU",
    latitude: -33.9399,
    longitude: 151.1753,
  },
] as const;

export const HUB_ROUTE_NETWORKS: Record<string, readonly HomepageDestination[]> = {
  LHR: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "13h 05m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 785,
      airlines: ["SQ", "BA"],
      distanceKm: 10889,
      routePath: "/flights/london-to-singapore",
    },
    {
      cityName: "New York",
      citySlug: "new-york",
      iata: "JFK",
      airportName: "John F. Kennedy International Airport",
      countryName: "United States",
      countryIso2: "US",
      latitude: 40.6413,
      longitude: -73.7781,
      typicalDuration: "7h 55m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 475,
      airlines: ["BA", "VS", "AA", "DL"],
      distanceKm: 5555,
      routePath: "/flights/london-to-new-york",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "14h 20m",
      durationRange: "13h - 15h",
      shortestDurationMinutes: 860,
      airlines: ["BA", "JL", "NH"],
      distanceKm: 9585,
      routePath: "/flights/london-to-tokyo",
    },
    {
      cityName: "Dubai",
      citySlug: "dubai",
      iata: "DXB",
      airportName: "Dubai International Airport",
      countryName: "United Arab Emirates",
      countryIso2: "AE",
      latitude: 25.2532,
      longitude: 55.3657,
      typicalDuration: "7h 05m",
      durationRange: "6h - 8h",
      shortestDurationMinutes: 425,
      airlines: ["EK", "BA"],
      distanceKm: 5470,
      routePath: "/flights/london-to-dubai",
    },
    {
      cityName: "Bangkok",
      citySlug: "bangkok",
      iata: "BKK",
      airportName: "Suvarnabhumi Airport",
      countryName: "Thailand",
      countryIso2: "TH",
      latitude: 13.69,
      longitude: 100.7501,
      typicalDuration: "11h 35m",
      durationRange: "11h - 13h",
      shortestDurationMinutes: 695,
      airlines: ["TG", "BR"],
      distanceKm: 9550,
      routePath: "/flights/london-to-bangkok",
    },
    {
      cityName: "Paris",
      citySlug: "paris",
      iata: "CDG",
      airportName: "Charles de Gaulle Airport",
      countryName: "France",
      countryIso2: "FR",
      latitude: 49.0097,
      longitude: 2.5479,
      typicalDuration: "1h 20m",
      durationRange: "1h - 2h",
      shortestDurationMinutes: 80,
      airlines: ["AF", "BA"],
      distanceKm: 344,
      routePath: "/flights/london-to-paris",
    },
  ],
  SIN: [
    {
      cityName: "London",
      citySlug: "london",
      iata: "LHR",
      airportName: "Heathrow Airport",
      countryName: "United Kingdom",
      countryIso2: "GB",
      latitude: 51.47,
      longitude: -0.4543,
      typicalDuration: "13h 40m",
      durationRange: "13h - 15h",
      shortestDurationMinutes: 820,
      airlines: ["SQ", "BA"],
      distanceKm: 10889,
      routePath: "/flights/singapore-to-london",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "7h 00m",
      durationRange: "6h - 8h",
      shortestDurationMinutes: 420,
      airlines: ["SQ", "JL", "NH"],
      distanceKm: 5310,
      routePath: "/flights/singapore-to-tokyo",
    },
    {
      cityName: "Bangkok",
      citySlug: "bangkok",
      iata: "BKK",
      airportName: "Suvarnabhumi Airport",
      countryName: "Thailand",
      countryIso2: "TH",
      latitude: 13.69,
      longitude: 100.7501,
      typicalDuration: "2h 25m",
      durationRange: "2h - 3h",
      shortestDurationMinutes: 145,
      airlines: ["SQ", "TG", "3K"],
      distanceKm: 1430,
      routePath: "/flights/singapore-to-bangkok",
    },
    {
      cityName: "Sydney",
      citySlug: "sydney",
      iata: "SYD",
      airportName: "Sydney Kingsford Smith Airport",
      countryName: "Australia",
      countryIso2: "AU",
      latitude: -33.9399,
      longitude: 151.1753,
      typicalDuration: "7h 50m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 470,
      airlines: ["SQ", "QF", "TR"],
      distanceKm: 6300,
      routePath: "/flights/singapore-to-sydney",
    },
    {
      cityName: "Dubai",
      citySlug: "dubai",
      iata: "DXB",
      airportName: "Dubai International Airport",
      countryName: "United Arab Emirates",
      countryIso2: "AE",
      latitude: 25.2532,
      longitude: 55.3657,
      typicalDuration: "7h 30m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 450,
      airlines: ["EK", "SQ"],
      distanceKm: 5840,
      routePath: "/flights/singapore-to-dubai",
    },
    {
      cityName: "Ho Chi Minh City",
      citySlug: "ho-chi-minh-city",
      iata: "SGN",
      airportName: "Tan Son Nhat International Airport",
      countryName: "Vietnam",
      countryIso2: "VN",
      latitude: 10.8188,
      longitude: 106.6519,
      typicalDuration: "2h 05m",
      durationRange: "2h - 3h",
      shortestDurationMinutes: 125,
      airlines: ["SQ", "VN", "VJ"],
      distanceKm: 1090,
      routePath: "/flights/singapore-to-ho-chi-minh-city",
    },
  ],
  BKK: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "2h 25m",
      durationRange: "2h - 3h",
      shortestDurationMinutes: 145,
      airlines: ["TG", "SQ", "3K"],
      distanceKm: 1430,
      routePath: "/flights/bangkok-to-singapore",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "5h 50m",
      durationRange: "5h - 7h",
      shortestDurationMinutes: 350,
      airlines: ["TG", "JL", "NH"],
      distanceKm: 4600,
      routePath: "/flights/bangkok-to-tokyo",
    },
    {
      cityName: "London",
      citySlug: "london",
      iata: "LHR",
      airportName: "Heathrow Airport",
      countryName: "United Kingdom",
      countryIso2: "GB",
      latitude: 51.47,
      longitude: -0.4543,
      typicalDuration: "12h 45m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 765,
      airlines: ["TG", "BR"],
      distanceKm: 9550,
      routePath: "/flights/bangkok-to-london",
    },
    {
      cityName: "Paris",
      citySlug: "paris",
      iata: "CDG",
      airportName: "Charles de Gaulle Airport",
      countryName: "France",
      countryIso2: "FR",
      latitude: 49.0097,
      longitude: 2.5479,
      typicalDuration: "12h 30m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 750,
      airlines: ["TG", "AF"],
      distanceKm: 9440,
      routePath: "/flights/bangkok-to-paris",
    },
    {
      cityName: "Dubai",
      citySlug: "dubai",
      iata: "DXB",
      airportName: "Dubai International Airport",
      countryName: "United Arab Emirates",
      countryIso2: "AE",
      latitude: 25.2532,
      longitude: 55.3657,
      typicalDuration: "6h 20m",
      durationRange: "6h - 8h",
      shortestDurationMinutes: 380,
      airlines: ["EK", "TG"],
      distanceKm: 4900,
      routePath: "/flights/bangkok-to-dubai",
    },
  ],
  HND: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "7h 15m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 435,
      airlines: ["SQ", "JL", "NH"],
      distanceKm: 5310,
      routePath: "/flights/tokyo-to-singapore",
    },
    {
      cityName: "Sydney",
      citySlug: "sydney",
      iata: "SYD",
      airportName: "Sydney Kingsford Smith Airport",
      countryName: "Australia",
      countryIso2: "AU",
      latitude: -33.9399,
      longitude: 151.1753,
      typicalDuration: "9h 45m",
      durationRange: "9h - 11h",
      shortestDurationMinutes: 585,
      airlines: ["NH", "JL", "QF"],
      distanceKm: 7829,
      routePath: "/flights/tokyo-to-sydney",
    },
    {
      cityName: "London",
      citySlug: "london",
      iata: "LHR",
      airportName: "Heathrow Airport",
      countryName: "United Kingdom",
      countryIso2: "GB",
      latitude: 51.47,
      longitude: -0.4543,
      typicalDuration: "14h 50m",
      durationRange: "14h - 16h",
      shortestDurationMinutes: 890,
      airlines: ["JL", "NH", "BA"],
      distanceKm: 9585,
      routePath: "/flights/tokyo-to-london",
    },
    {
      cityName: "New York",
      citySlug: "new-york",
      iata: "JFK",
      airportName: "John F. Kennedy International Airport",
      countryName: "United States",
      countryIso2: "US",
      latitude: 40.6413,
      longitude: -73.7781,
      typicalDuration: "12h 45m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 765,
      airlines: ["JL", "NH", "AA"],
      distanceKm: 10850,
      routePath: "/flights/tokyo-to-new-york",
    },
  ],
  JFK: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "18h 50m",
      durationRange: "18h - 19h",
      shortestDurationMinutes: 1130,
      airlines: ["SQ"],
      distanceKm: 15348,
      routePath: "/flights/new-york-to-singapore",
    },
    {
      cityName: "London",
      citySlug: "london",
      iata: "LHR",
      airportName: "Heathrow Airport",
      countryName: "United Kingdom",
      countryIso2: "GB",
      latitude: 51.47,
      longitude: -0.4543,
      typicalDuration: "7h 05m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 425,
      airlines: ["BA", "VS", "AA", "DL"],
      distanceKm: 5555,
      routePath: "/flights/new-york-to-london",
    },
    {
      cityName: "Paris",
      citySlug: "paris",
      iata: "CDG",
      airportName: "Charles de Gaulle Airport",
      countryName: "France",
      countryIso2: "FR",
      latitude: 49.0097,
      longitude: 2.5479,
      typicalDuration: "7h 20m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 440,
      airlines: ["AF", "DL", "AA"],
      distanceKm: 5836,
      routePath: "/flights/new-york-to-paris",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "14h 10m",
      durationRange: "14h - 16h",
      shortestDurationMinutes: 850,
      airlines: ["JL", "NH", "AA"],
      distanceKm: 10850,
      routePath: "/flights/new-york-to-tokyo",
    },
    {
      cityName: "Dubai",
      citySlug: "dubai",
      iata: "DXB",
      airportName: "Dubai International Airport",
      countryName: "United Arab Emirates",
      countryIso2: "AE",
      latitude: 25.2532,
      longitude: 55.3657,
      typicalDuration: "12h 30m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 750,
      airlines: ["EK"],
      distanceKm: 11000,
      routePath: "/flights/new-york-to-dubai",
    },
  ],
  CDG: [
    {
      cityName: "New York",
      citySlug: "new-york",
      iata: "JFK",
      airportName: "John F. Kennedy International Airport",
      countryName: "United States",
      countryIso2: "US",
      latitude: 40.6413,
      longitude: -73.7781,
      typicalDuration: "8h 15m",
      durationRange: "8h - 10h",
      shortestDurationMinutes: 495,
      airlines: ["AF", "DL", "AA"],
      distanceKm: 5836,
      routePath: "/flights/paris-to-new-york",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "14h 05m",
      durationRange: "13h - 15h",
      shortestDurationMinutes: 845,
      airlines: ["AF", "JL", "NH"],
      distanceKm: 9710,
      routePath: "/flights/paris-to-tokyo",
    },
    {
      cityName: "Dubai",
      citySlug: "dubai",
      iata: "DXB",
      airportName: "Dubai International Airport",
      countryName: "United Arab Emirates",
      countryIso2: "AE",
      latitude: 25.2532,
      longitude: 55.3657,
      typicalDuration: "6h 40m",
      durationRange: "6h - 8h",
      shortestDurationMinutes: 400,
      airlines: ["EK", "AF"],
      distanceKm: 5240,
      routePath: "/flights/paris-to-dubai",
    },
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "12h 55m",
      durationRange: "12h - 14h",
      shortestDurationMinutes: 775,
      airlines: ["AF", "SQ"],
      distanceKm: 10730,
      routePath: "/flights/paris-to-singapore",
    },
  ],
  DXB: [
    {
      cityName: "London",
      citySlug: "london",
      iata: "LHR",
      airportName: "Heathrow Airport",
      countryName: "United Kingdom",
      countryIso2: "GB",
      latitude: 51.47,
      longitude: -0.4543,
      typicalDuration: "7h 45m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 465,
      airlines: ["EK", "BA"],
      distanceKm: 5470,
      routePath: "/flights/dubai-to-london",
    },
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "7h 35m",
      durationRange: "7h - 9h",
      shortestDurationMinutes: 455,
      airlines: ["EK", "SQ"],
      distanceKm: 5840,
      routePath: "/flights/dubai-to-singapore",
    },
    {
      cityName: "New York",
      citySlug: "new-york",
      iata: "JFK",
      airportName: "John F. Kennedy International Airport",
      countryName: "United States",
      countryIso2: "US",
      latitude: 40.6413,
      longitude: -73.7781,
      typicalDuration: "14h 20m",
      durationRange: "14h - 16h",
      shortestDurationMinutes: 860,
      airlines: ["EK"],
      distanceKm: 11000,
      routePath: "/flights/dubai-to-new-york",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "9h 30m",
      durationRange: "9h - 11h",
      shortestDurationMinutes: 570,
      airlines: ["EK"],
      distanceKm: 7930,
      routePath: "/flights/dubai-to-tokyo",
    },
  ],
  SGN: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "2h 05m",
      durationRange: "2h - 3h",
      shortestDurationMinutes: 125,
      airlines: ["VN", "SQ", "VJ"],
      distanceKm: 1090,
      routePath: "/flights/ho-chi-minh-city-to-singapore",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "5h 45m",
      durationRange: "5h - 7h",
      shortestDurationMinutes: 345,
      airlines: ["VN", "JL", "NH"],
      distanceKm: 4320,
      routePath: "/flights/ho-chi-minh-city-to-tokyo",
    },
    {
      cityName: "Bangkok",
      citySlug: "bangkok",
      iata: "BKK",
      airportName: "Suvarnabhumi Airport",
      countryName: "Thailand",
      countryIso2: "TH",
      latitude: 13.69,
      longitude: 100.7501,
      typicalDuration: "1h 35m",
      durationRange: "1h - 2h",
      shortestDurationMinutes: 95,
      airlines: ["VN", "TG", "VJ"],
      distanceKm: 750,
      routePath: "/flights/ho-chi-minh-city-to-bangkok",
    },
    {
      cityName: "Sydney",
      citySlug: "sydney",
      iata: "SYD",
      airportName: "Sydney Kingsford Smith Airport",
      countryName: "Australia",
      countryIso2: "AU",
      latitude: -33.9399,
      longitude: 151.1753,
      typicalDuration: "8h 40m",
      durationRange: "8h - 10h",
      shortestDurationMinutes: 520,
      airlines: ["VN", "JQ"],
      distanceKm: 6850,
      routePath: "/flights/ho-chi-minh-city-to-sydney",
    },
  ],
  SYD: [
    {
      cityName: "Singapore",
      citySlug: "singapore",
      iata: "SIN",
      airportName: "Singapore Changi Airport",
      countryName: "Singapore",
      countryIso2: "SG",
      latitude: 1.3644,
      longitude: 103.9915,
      typicalDuration: "8h 15m",
      durationRange: "8h - 10h",
      shortestDurationMinutes: 495,
      airlines: ["QF", "SQ", "TR"],
      distanceKm: 6300,
      routePath: "/flights/sydney-to-singapore",
    },
    {
      cityName: "Tokyo",
      citySlug: "tokyo",
      iata: "HND",
      airportName: "Haneda Airport",
      countryName: "Japan",
      countryIso2: "JP",
      latitude: 35.5494,
      longitude: 139.7798,
      typicalDuration: "9h 50m",
      durationRange: "9h - 11h",
      shortestDurationMinutes: 590,
      airlines: ["QF", "NH", "JL"],
      distanceKm: 7829,
      routePath: "/flights/sydney-to-tokyo",
    },
  ],
};

export const DEFAULT_ORIGIN_HUB =
  HUB_AIRPORTS.find((hub) => hub.iata === "JFK") ?? HUB_AIRPORTS[0]!; // New York JFK default fallback

export function findHub(query: string): HubAirport | undefined {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return undefined;

  return HUB_AIRPORTS.find(
    (hub) =>
      hub.iata.toLowerCase() === normalized ||
      hub.citySlug.toLowerCase() === normalized ||
      hub.cityName.toLowerCase() === normalized ||
      hub.countryName.toLowerCase() === normalized,
  );
}

export function searchHubs(query: string, limit = 6): HubAirport[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return HUB_AIRPORTS.slice(0, limit);

  return HUB_AIRPORTS.filter(
    (hub) =>
      hub.iata.toLowerCase().includes(normalized) ||
      hub.cityName.toLowerCase().includes(normalized) ||
      hub.countryName.toLowerCase().includes(normalized) ||
      hub.name.toLowerCase().includes(normalized),
  ).slice(0, limit);
}

export function getHubRouteNetwork(hub: HubAirport): HubRouteNetwork {
  const destinations = HUB_ROUTE_NETWORKS[hub.iata] ?? [];
  return {
    origin: hub,
    destinations,
  };
}
