import type { CityPageModel } from "./city-page-model";

export const BANGKOK_CITY_PAGE_FIXTURE: CityPageModel = {
  city: { name: "Bangkok", slug: "bangkok" },
  country: { name: "Thailand", slug: "thailand", region: "Asia" },
  seo: {
    h1: "Direct flights from Bangkok",
    subheadline: "Explore nonstop destinations across Asia, Europe, and beyond",
    title: "Direct Flights from Bangkok: Routes & Airlines | Tripways",
    description:
      "Explore nonstop destinations accessible from Thailand's primary aviation hubs across Suvarnabhumi (BKK) and Don Mueang (DMK).",
    intro:
      "Explore nonstop destinations accessible from Thailand's primary aviation hubs. Whether you're departing from Suvarnabhumi (BKK) or Don Mueang (DMK), find direct connections across Asia, Europe, and beyond.",
  },
  quickFacts: {
    destinations: 182,
    countries: 67,
    airlines: 48,
    airports: 2,
  },
  airports: [
    {
      iata: "BKK",
      name: "Suvarnabhumi Airport",
      primary: true,
      destinations: 128,
      airlines: 84,
      role: "Primary Hub",
      description:
        "Bangkok's main long-haul and full-service international gateway.",
    },
    {
      iata: "DMK",
      name: "Don Mueang International Airport",
      primary: false,
      destinations: 64,
      airlines: 12,
      role: "LCC Hub",
      description:
        "Bangkok's main domestic and regional low-cost carrier terminal.",
    },
  ],
  destinations: [
    {
      city: "Singapore",
      citySlug: "singapore",
      country: "Singapore",
      region: "SE Asia",
      originAirports: ["BKK", "DMK"],
      airports: ["SIN"],
      airlines: ["SQ", "TG", "3K", "TR"],
      frequency: 84,
      minDuration: 145,
      maxDuration: 160,
      path: "/flights/bangkok-to-singapore",
      fareMin: 45,
      fareMax: 85,
    },
    {
      city: "Tokyo",
      citySlug: "tokyo",
      country: "Japan",
      region: "East Asia",
      originAirports: ["BKK", "DMK"],
      airports: ["NRT", "HND"],
      airlines: ["TG", "JL", "NH", "XJ"],
      frequency: 70,
      minDuration: 375,
      maxDuration: 405,
      path: "/flights/bangkok-to-tokyo",
      fareMin: 180,
      fareMax: 320,
    },
    {
      city: "London",
      citySlug: "london",
      country: "United Kingdom",
      region: "Europe",
      originAirports: ["BKK"],
      airports: ["LHR"],
      airlines: ["TG", "BR", "BA"],
      frequency: 28,
      minDuration: 765,
      maxDuration: 810,
      path: "/flights/bangkok-to-london",
      fareMin: 350,
      fareMax: 650,
    },
    {
      city: "Hong Kong",
      citySlug: "hong-kong",
      country: "Hong Kong",
      region: "East Asia",
      originAirports: ["BKK", "DMK"],
      airports: ["HKG"],
      airlines: ["CX", "TG", "EK", "UO"],
      frequency: 75,
      minDuration: 175,
      maxDuration: 195,
      path: "/flights/bangkok-to-hong-kong",
      fareMin: 85,
      fareMax: 160,
    },
    {
      city: "Sydney",
      citySlug: "sydney",
      country: "Australia",
      region: "Oceania",
      originAirports: ["BKK"],
      airports: ["SYD"],
      airlines: ["TG", "QF", "JQ"],
      frequency: 21,
      minDuration: 550,
      maxDuration: 580,
      path: "/flights/bangkok-to-sydney",
      fareMin: 350,
      fareMax: 580,
    },
    {
      city: "Phuket",
      citySlug: "phuket",
      country: "Thailand",
      region: "SE Asia",
      originAirports: ["BKK", "DMK"],
      airports: ["HKT"],
      airlines: ["TG", "PG", "VZ", "FD"],
      frequency: 150,
      minDuration: 85,
      maxDuration: 95,
      path: "/flights/bangkok-to-phuket",
      fareMin: 25,
      fareMax: 50,
    },
    {
      city: "Paris",
      citySlug: "paris",
      country: "France",
      region: "Europe",
      originAirports: ["BKK"],
      airports: ["CDG"],
      airlines: ["TG", "AF"],
      frequency: 14,
      minDuration: 770,
      maxDuration: 815,
      path: "/flights/bangkok-to-paris",
      fareMin: 380,
      fareMax: 690,
    },
    {
      city: "Dubai",
      citySlug: "dubai",
      country: "United Arab Emirates",
      region: "Middle East",
      originAirports: ["BKK"],
      airports: ["DXB"],
      airlines: ["EK", "FZ"],
      frequency: 35,
      minDuration: 380,
      maxDuration: 410,
      path: "/flights/bangkok-to-dubai",
      fareMin: 210,
      fareMax: 410,
    },
  ],
  faqs: [
    {
      question: "Which airports serve Bangkok?",
      answer:
        "Suvarnabhumi (BKK) is the primary hub for legacy carriers like Thai Airways, Emirates, and Singapore Airlines, offering nonstop long-haul and full-service flights. Don Mueang (DMK) is a hub for low-cost carriers like AirAsia and Nok Air, specializing in domestic Thai flights and regional routes within Asia.",
    },
    {
      question: "How many nonstop destinations can I reach from Bangkok?",
      answer:
        "You can fly nonstop to over 180 direct destinations across Asia, Europe, Australia, and the Middle East from Bangkok's two airports.",
    },
    {
      question: "How do I know whether a route departs from BKK or DMK?",
      answer:
        "Full-service and intercontinental flights predominantly operate out of Suvarnabhumi (BKK), while budget carriers and domestic regional flights frequently depart from Don Mueang (DMK). Check the Origin badge on each route for exact departure terminals.",
    },
  ],
  links: [
    {
      title: "BANGKOK AIRPORT HUBS",
      links: [
        {
          label: "Explore flights from Suvarnabhumi (BKK)",
          href: "/airports/bkk",
        },
        {
          label: "Explore flights from Don Mueang (DMK)",
          href: "/airports/dmk",
        },
      ],
    },
    {
      title: "DIRECT DESTINATIONS BY COUNTRY",
      links: [
        {
          label: "Flights from Bangkok to Japan",
          href: "/flights-from/bangkok?destination_countries=JP",
        },
        {
          label: "Flights from Bangkok to Singapore",
          href: "/flights/bangkok-to-singapore",
        },
        {
          label: "Flights from Bangkok to the United Kingdom",
          href: "/flights-from/bangkok?destination_countries=GB",
        },
        {
          label: "Flights from Bangkok to Australia",
          href: "/flights-from/bangkok?destination_countries=AU",
        },
        {
          label: "Flights from Bangkok to Vietnam",
          href: "/flights-from/bangkok?destination_countries=VN",
        },
      ],
    },
    {
      title: "OTHER THAI DEPARTURE HUBS",
      links: [
        {
          label: "Direct flights from Phuket",
          href: "/flights-from/phuket",
        },
        {
          label: "Direct flights from Chiang Mai",
          href: "/flights-from/chiang-mai",
        },
        {
          label: "Direct flights from Koh Samui",
          href: "/flights-from/koh-samui",
        },
        {
          label: "Direct flights from Krabi",
          href: "/flights-from/krabi",
        },
      ],
    },
  ],
  freshnessAt: "2026-08-04",
  canonicalPath: "/flights-from/bangkok",
};
